// Covers every nation name that appears in src/data/squads.json. A handful of
// tournament entries are dissolved states with no current flag (USSR, East
// and West Germany, Yugoslavia, Czechoslovakia, Serbia and Montenegro,
// Zaire) - those fall back to a neutral badge. The four UK home nations
// (England, Scotland, Wales, Northern Ireland) don't have their own ISO
// flag; the Union Jack is used for all of them rather than the less
// reliably-rendered subdivision flag sequences.
const FLAGS: Record<string, string> = {
  Algeria: '🇩🇿',
  Angola: '🇦🇴',
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Belgium: '🇧🇪',
  Bolivia: '🇧🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  Brazil: '🇧🇷',
  Bulgaria: '🇧🇬',
  'Cabo Verde': '🇨🇻',
  Cameroon: '🇨🇲',
  Canada: '🇨🇦',
  Chile: '🇨🇱',
  China: '🇨🇳',
  Colombia: '🇨🇴',
  'Congo DR': '🇨🇩',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  Curaçao: '🇨🇼',
  'Czech Republic': '🇨🇿',
  Czechia: '🇨🇿',
  "Côte d'Ivoire": '🇨🇮',
  Denmark: '🇩🇰',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  'El Salvador': '🇸🇻',
  England: '🇬🇧',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Greece: '🇬🇷',
  Haiti: '🇭🇹',
  Honduras: '🇭🇳',
  Hungary: '🇭🇺',
  'IR Iran': '🇮🇷',
  Iceland: '🇮🇸',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  Israel: '🇮🇱',
  Italy: '🇮🇹',
  'Ivory Coast': '🇨🇮',
  Jamaica: '🇯🇲',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Kuwait: '🇰🇼',
  Mexico: '🇲🇽',
  Morocco: '🇲🇦',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nigeria: '🇳🇬',
  'North Korea': '🇰🇵',
  'Northern Ireland': '🇬🇧',
  Norway: '🇳🇴',
  Panama: '🇵🇦',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  Qatar: '🇶🇦',
  'Republic of Ireland': '🇮🇪',
  Romania: '🇷🇴',
  Russia: '🇷🇺',
  'Saudi Arabia': '🇸🇦',
  Scotland: '🇬🇧',
  Senegal: '🇸🇳',
  Serbia: '🇷🇸',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  Spain: '🇪🇸',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Togo: '🇹🇬',
  'Trinidad and Tobago': '🇹🇹',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  Türkiye: '🇹🇷',
  USA: '🇺🇸',
  Ukraine: '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Wales: '🇬🇧',
}

export function flagFor(team: string): string {
  return FLAGS[team] ?? '⚽'
}
