import { POSITIONS } from '../engine/positions'
import type { Player, Position, Squad } from '../types'

function isPosition(value: unknown): value is Position {
  return typeof value === 'string' && (POSITIONS as string[]).includes(value)
}

function assertPlayer(raw: unknown, squadId: string): Player {
  const p = raw as Player
  if (typeof p.id !== 'string' || !p.id) {
    throw new Error(`${squadId}: a player is missing an id`)
  }
  if (typeof p.overall !== 'number' || p.overall < 1 || p.overall > 99) {
    throw new Error(`${squadId}: ${p.id} has an invalid overall (${p.overall})`)
  }
  if (!Array.isArray(p.positions) || p.positions.length === 0) {
    throw new Error(`${squadId}: ${p.id} has no positions`)
  }
  for (const position of p.positions) {
    if (!isPosition(position)) {
      throw new Error(`${squadId}: ${p.id} has an unknown position "${position}"`)
    }
  }
  return p
}

function assertSquad(raw: unknown): Squad {
  const s = raw as Squad
  if (typeof s.id !== 'string' || !s.id) {
    throw new Error('a squad is missing an id')
  }
  if (!Array.isArray(s.players) || s.players.length === 0) {
    throw new Error(`${s.id}: squad has no players`)
  }
  for (const player of s.players) {
    assertPlayer(player, s.id)
  }
  return s
}

// squads.json is ~2MB (400+ real World Cup squads, generated by
// scripts/generate-squads.mjs) - loaded lazily via dynamic import so it isn't
// bundled into the app's main chunk, and cached after the first load.
let cachedSquads: Squad[] | null = null

export async function loadSquads(): Promise<Squad[]> {
  if (cachedSquads) return cachedSquads
  const module = await import('./squads.json')
  const raw = module.default as unknown[]
  cachedSquads = raw.map(assertSquad)
  return cachedSquads
}
